import {
  NODEUO_PAYLOAD_SCHEMAS,
  NODEUO_SCHEMA_VERSION,
  schemaFingerprintForFeature,
  stableJsonFingerprint,
  validateFeaturePayload,
} from './manifest.js';

function tsType(schema = {}, depth = 0) {
  if (depth > 8) return 'unknown';
  if (Array.isArray(schema.enum)) return schema.enum.map((value) => JSON.stringify(value)).join(' | ');
  if (schema.type === 'string') return 'string';
  if (schema.type === 'integer' || schema.type === 'number') return 'number';
  if (schema.type === 'boolean') return 'boolean';
  if (schema.type === 'array') return `ReadonlyArray<${schema.items ? tsType(schema.items, depth + 1) : 'unknown'}>`;
  if (schema.type === 'object') {
    const required = new Set(schema.required ?? []);
    const fields = Object.entries(schema.properties ?? {}).map(([key, value]) =>
      `readonly ${JSON.stringify(key)}${required.has(key) ? '' : '?'}: ${tsType(value, depth + 1)};`);
    return fields.length ? `{ ${fields.join(' ')} }` : 'Readonly<Record<string, unknown>>';
  }
  return 'unknown';
}

/** Generate dependency-free declarations from the same schemas used by both
 * runtimes. The output is intentionally plain TypeScript and may be consumed
 * by Script Studio, alternative clients, or external tooling. */
export function generateNodeUOTypeDefinitions() {
  const ids = Object.keys(NODEUO_PAYLOAD_SCHEMAS).sort();
  const lines = [
    '// Generated by @uo/nodeuo-protocol. Do not edit by hand.',
    `export const NODEUO_SCHEMA_VERSION: ${NODEUO_SCHEMA_VERSION};`,
    `export type NodeUOFeatureId = ${ids.map((id) => JSON.stringify(id)).join(' | ')};`,
    'export interface NodeUOPayloadByFeature {',
  ];
  for (const id of ids) lines.push(`  readonly ${JSON.stringify(id)}: ${tsType(NODEUO_PAYLOAD_SCHEMAS[id])};`);
  lines.push('}', 'export type NodeUOPayload<F extends NodeUOFeatureId> = NodeUOPayloadByFeature[F];');
  return `${lines.join('\n')}\n`;
}

function exampleFor(schema = {}, depth = 0) {
  if (depth > 8) return null;
  if (schema.enum?.length) return schema.enum[0];
  if (schema.type === 'string') return 'example';
  if (schema.type === 'integer' || schema.type === 'number') return Math.max(0, Number(schema.minimum) || 0);
  if (schema.type === 'boolean') return false;
  if (schema.type === 'array') return [];
  if (schema.type === 'object') return Object.fromEntries((schema.required ?? [])
    .map((key) => [key, exampleFor(schema.properties?.[key] ?? {}, depth + 1)]));
  return null;
}

export function buildNodeUOConformanceFixtures() {
  const fixtures = Object.keys(NODEUO_PAYLOAD_SCHEMAS).sort().map((feature) => {
    const payload = exampleFor(NODEUO_PAYLOAD_SCHEMAS[feature]);
    const validation = validateFeaturePayload(feature, payload);
    return Object.freeze({ feature, schema: schemaFingerprintForFeature(feature), payload,
      valid: validation.ok, errors: validation.errors });
  });
  return Object.freeze({ schemaVersion: NODEUO_SCHEMA_VERSION,
    fingerprint: `fnv1a64:${stableJsonFingerprint(fixtures)}`, fixtures: Object.freeze(fixtures) });
}
