import js from '@eslint/js';

const readonly = (names) => Object.fromEntries(names.map((name) => [name, 'readonly']));

const sharedGlobals = {
  ...readonly([
    'AbortController',
    'AbortSignal',
    'Blob',
    'Buffer',
    'CustomEvent',
    'DOMParser',
    'Event',
    'File',
    'FileReader',
    'FormData',
    'Headers',
    'Image',
    'ImageBitmap',
    'ImageData',
    'KeyboardEvent',
    'MouseEvent',
    'MutationObserver',
    'OffscreenCanvas',
    'PointerEvent',
    'Promise',
    'ReadableStream',
    'Request',
    'ResizeObserver',
    'Response',
    'TextDecoder',
    'TextEncoder',
    'URL',
    'URLSearchParams',
    'WebSocket',
    'Worker',
    'XMLSerializer',
    '__APP_VERSION__',
    'atob',
    'btoa',
    'cancelAnimationFrame',
    'clearImmediate',
    'clearInterval',
    'clearTimeout',
    'console',
    'crypto',
    'devicePixelRatio',
    'document',
    'fetch',
    'globalThis',
    'history',
    'indexedDB',
    'innerHeight',
    'innerWidth',
    'localStorage',
    'location',
    'module',
    'navigator',
    'performance',
    'process',
    'queueMicrotask',
    'requestAnimationFrame',
    'sessionStorage',
    'setImmediate',
    'setInterval',
    'setTimeout',
    'self',
    'SpeechSynthesisUtterance',
    'structuredClone',
    'window',
    'HTMLInputElement',
    'HTMLTextAreaElement',
    'DecompressionStream',
  ]),
  Audio: 'readonly',
  HTMLElement: 'readonly',
  HTMLCanvasElement: 'readonly',
  HTMLImageElement: 'readonly',
};

export default [
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/coverage/**',
      'apps/client/public/assets/**',
      'templates/**',
      'saves/**',
    ],
  },
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'module',
      globals: sharedGlobals,
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-constant-condition': ['error', { checkLoops: false }],
      'no-empty': ['error', { allowEmptyCatch: true }],
      // Several protocol and terminal helpers intentionally match ASCII
      // control ranges; treating those regexes as lint failures obscures
      // real runtime problems.
      'no-control-regex': 'off',
    },
  },
  {
    files: ['**/*.cjs'],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'commonjs',
      globals: {
        ...sharedGlobals,
        __dirname: 'readonly',
        __filename: 'readonly',
        exports: 'writable',
        require: 'readonly',
      },
    },
  },
  {
    files: ['**/*.test.js', '**/*.spec.js'],
    languageOptions: {
      globals: readonly([
        'afterAll',
        'afterEach',
        'beforeAll',
        'beforeEach',
        'describe',
        'expect',
        'it',
        'test',
        'vi',
      ]),
    },
  },
  {
    files: ['apps/client/public/**/*.js'],
    languageOptions: {
      globals: readonly([
        'caches',
        'clients',
        'importScripts',
        'registration',
        'self',
        'skipWaiting',
      ]),
    },
  },
];
